#!/bin/bash

hook_name="$(basename "$0")"

echo $hook_name

# Run tests as hook
for script in "$0".d/*; do
	# Don't run disabled tests
	if ! [[ "$script" =~ \.disabled$ ]]; then
		GIT_HOOK=$hook_name "$script" || exit 1
	fi
done
