#!/bin/bash

# Exit if any commands fail
# This aborts the commit if used as a git hook
set -e

only_scripts() {
	while IFS= read -r file; do
		if [[ -f "$file" ]]; then
			firstline=$(head -n 1 "$file")
			if [[ "$firstline" =~ '#!/bin/'(ba)?sh ]] || [[ "$file" =~ .sh$ ]]; then
				echo "$file"
			fi
		fi
	done
}

for dep in shfmt shellcheck; do
	if ! command -v "$dep" >/dev/null; then
		echo "ERROR: Hook dependency $dep not found in \$PATH" >&2
		exit 1
	fi
done

if [[ -n "$GIT_HOOK" ]]; then
	# If we are running as a pre-commit hook, only check the staged files
	# If grep has no results, this will fail. Disable -e temporarily.
	set +e
	staged_files="$(git diff --name-only --cached | only_scripts)"
	set -e
else
	# Otherwise, check all shell files
	staged_files="$(shfmt -f .)"
fi

if [[ -z "$staged_files" ]]; then
	echo 'No files to check.'
	exit 0
fi

# Prettify first in case it affects linting
echo 'Prettifying...'
for file in $staged_files; do
	# Use shfmt to prettify
	shfmt -l -w -i 0 "$file"
	# Add the fixed files back the the staging area
	# This only happens within the precommit hook, which uses git stash beforehand!
	if [[ -n "$GIT_HOOK" ]]; then
		git add "$file"
	fi
done

# Now lint using shellcheck
echo 'Linting...'
for file in $staged_files; do
	shellcheck "$file"
done
